name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]
    
# note that your "main" branch might be called main instead of master

# this comment was added for exercise 11.13

# this comment was added for exercise 11.17 since that was a web-based configuration
# Require all status checks to pass before merging
# Require all pull request to be approved before merging

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
      #     command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:8000
      - name: Deploy app
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
      - name: Test Info
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ success() }}
        with:
            severity: info
            details: Test succeeded.
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Test Error
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ failure() }}
        with:
            severity: error
            details: Test error.
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
